<?php
declare(strict_types=1); require __DIR__.'/config.php';
ini_set('display_errors','0'); error_reporting(E_ALL);
if(session_status()!==PHP_SESSION_ACTIVE){session_set_cookie_params(['httponly'=>true,'samesite'=>'Lax','secure'=>!empty($_SERVER['HTTPS'])]);session_start();}
function db():PDO{static $d=null;if($d instanceof PDO)return $d;if(!is_dir(dirname(DB_FILE)))mkdir(dirname(DB_FILE),0770,true);$d=new PDO('sqlite:'.DB_FILE,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$d->exec('CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE,password_hash TEXT,role TEXT,created_at TEXT)');$d->exec('CREATE TABLE IF NOT EXISTS offers(id INTEGER PRIMARY KEY,offer_no TEXT UNIQUE,original_name TEXT,stored_path TEXT,client TEXT,offer_date TEXT,author TEXT,created_at TEXT,updated_at TEXT)');if((int)$d->query('SELECT COUNT(*) FROM users')->fetchColumn()===0){$s=$d->prepare('INSERT INTO users(username,password_hash,role,created_at) VALUES(?,?,?,?)');$s->execute(['admin',password_hash('admin123',PASSWORD_DEFAULT),'admin',date(DATE_ATOM)]);}return $d;}
function out($x,$c=200):never{http_response_code($c);header('Content-Type: application/json; charset=utf-8');echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function auth():void{if(empty($_SESSION['user']))out(['error'=>'Необходим е вход.'],401);}function admin():void{auth();if(($_SESSION['role']??'')!=='admin')out(['error'=>'Необходими са администраторски права.'],403);}function token():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));return $_SESSION['csrf'];}function check():void{$v=$_SERVER['HTTP_X_CSRF_TOKEN']??'';if(!hash_equals($_SESSION['csrf']??'',$v))out(['error'=>'Невалиден CSRF токен.'],403);}
function clean($s):string{return trim(preg_replace('/[\x00-\x1F\x7F]/u','',(string)$s));}function folder($date,$client):string{$dt=DateTime::createFromFormat('Y-m-d',$date);if(!$dt)throw new RuntimeException('Невалидна дата.');$c=trim(preg_replace('/[^\pL\pN._-]+/u','-',mb_strtolower($client)),'-')?:'bez-klient';return FILE_DIR.'/'.$dt->format('Y/m').'/'.$c;}function nextNo():string{$y=date('Y');$p="OF-$y-";$s=db()->prepare('SELECT offer_no FROM offers WHERE offer_no LIKE ? ORDER BY offer_no DESC LIMIT 1');$s->execute([$p.'%']);$v=$s->fetchColumn();return $p.str_pad((string)($v?(int)substr($v,-4)+1:1),4,'0',STR_PAD_LEFT);}
$a=$_GET['action']??'';
try{
if($a==='health')out(['ok'=>true,'php'=>PHP_VERSION,'pdo_sqlite'=>extension_loaded('pdo_sqlite'),'storage_writable'=>is_writable(__DIR__.'/storage')]);
if($a==='session')out(['user'=>$_SESSION['user']??null,'role'=>$_SESSION['role']??null,'csrf'=>!empty($_SESSION['user'])?token():null]);
if($a==='login'&&$_SERVER['REQUEST_METHOD']==='POST'){$i=json_decode(file_get_contents('php://input'),true)?:[];$s=db()->prepare('SELECT * FROM users WHERE username=?');$s->execute([trim($i['username']??'')]);$u=$s->fetch(PDO::FETCH_ASSOC);if(!$u||!password_verify($i['password']??'',$u['password_hash']))out(['error'=>'Невалидно потребителско име или парола.'],401);session_regenerate_id(true);$_SESSION['user']=$u['username'];$_SESSION['role']=$u['role'];out(['user'=>$u['username'],'role'=>$u['role'],'csrf'=>token()]);}
if($a==='logout'&&$_SERVER['REQUEST_METHOD']==='POST'){auth();check();session_destroy();out(['ok'=>true]);}

if($a==='users'&&$_SERVER['REQUEST_METHOD']==='GET'){admin();$r=db()->query('SELECT id,username,role,created_at FROM users ORDER BY username')->fetchAll(PDO::FETCH_ASSOC);out(['users'=>$r]);}
if($a==='user_create'&&$_SERVER['REQUEST_METHOD']==='POST'){admin();check();$i=json_decode(file_get_contents('php://input'),true)?:[];$name=clean($i['username']??'');$pass=(string)($i['password']??'');$role=($i['role']??'user')==='admin'?'admin':'user';if(!preg_match('/^[\pL\pN._-]{3,50}$/u',$name))out(['error'=>'Името трябва да е 3-50 символа и може да съдържа букви, цифри, точка, тире и долна черта.'],422);if(strlen($pass)<8)out(['error'=>'Паролата трябва да съдържа поне 8 символа.'],422);try{$q=db()->prepare('INSERT INTO users(username,password_hash,role,created_at) VALUES(?,?,?,?)');$q->execute([$name,password_hash($pass,PASSWORD_DEFAULT),$role,date(DATE_ATOM)]);}catch(PDOException $e){if(str_contains($e->getMessage(),'UNIQUE'))out(['error'=>'Потребителското име вече съществува.'],409);throw $e;}out(['ok'=>true]);}
if($a==='user_password'&&$_SERVER['REQUEST_METHOD']==='POST'){admin();check();$i=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($i['id']??0);$pass=(string)($i['password']??'');if(strlen($pass)<8)out(['error'=>'Паролата трябва да съдържа поне 8 символа.'],422);$q=db()->prepare('UPDATE users SET password_hash=? WHERE id=?');$q->execute([password_hash($pass,PASSWORD_DEFAULT),$id]);if(!$q->rowCount())out(['error'=>'Потребителят не е намерен.'],404);out(['ok'=>true]);}
if($a==='user_delete'&&$_SERVER['REQUEST_METHOD']==='POST'){admin();check();$i=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($i['id']??0);$q=db()->prepare('SELECT id,username,role FROM users WHERE id=?');$q->execute([$id]);$u=$q->fetch(PDO::FETCH_ASSOC);if(!$u)out(['error'=>'Потребителят не е намерен.'],404);if($u['username']===($_SESSION['user']??''))out(['error'=>'Не можете да изтриете активния си профил.'],422);if($u['role']==='admin'&&(int)db()->query("SELECT COUNT(*) FROM users WHERE role='admin'")->fetchColumn()<=1)out(['error'=>'Последният администратор не може да бъде изтрит.'],422);$d=db()->prepare('DELETE FROM users WHERE id=?');$d->execute([$id]);out(['ok'=>true]);}

if($a==='offers'){auth();$sql='SELECT id,offer_no,original_name,client,offer_date,author,updated_at FROM offers WHERE 1=1';$p=[];foreach(['client'=>'client','author'=>'author'] as $k=>$col)if(clean($_GET[$k]??'')!==''){$sql.=" AND $col=?";$p[]=clean($_GET[$k]);}$q=clean($_GET['q']??'');if($q!==''){$sql.=' AND (offer_no LIKE ? OR original_name LIKE ? OR client LIKE ?)';array_push($p,"%$q%","%$q%","%$q%");}if(clean($_GET['from']??'')!==''){$sql.=' AND offer_date>=?';$p[]=clean($_GET['from']);}if(clean($_GET['to']??'')!==''){$sql.=' AND offer_date<=?';$p[]=clean($_GET['to']);}$s=db()->prepare($sql.' ORDER BY offer_date DESC,id DESC');$s->execute($p);out(['offers'=>$s->fetchAll(PDO::FETCH_ASSOC)]);}
if($a==='save'&&$_SERVER['REQUEST_METHOD']==='POST'){auth();check();if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)out(['error'=>'Файлът не е получен.'],400);$f=$_FILES['file'];if($f['size']>MAX_FILE)out(['error'=>'Максималният размер е 20 MB.'],413);if(strtolower(pathinfo($f['name'],PATHINFO_EXTENSION))!=='xlsx')out(['error'=>'Разрешени са само .xlsx файлове.'],415);$client=clean($_POST['client']??'');$date=clean($_POST['offer_date']??'');if($client===''||$date==='')out(['error'=>'Клиентът и датата са задължителни.'],422);$id=(int)($_POST['id']??0);$old=null;$no=nextNo();if($id){$s=db()->prepare('SELECT * FROM offers WHERE id=?');$s->execute([$id]);$old=$s->fetch(PDO::FETCH_ASSOC);if(!$old)out(['error'=>'Офертата не е намерена.'],404);$no=$old['offer_no'];}$dir=folder($date,$client);if(!is_dir($dir))mkdir($dir,0770,true);$target=$dir.'/'.$no.'.xlsx';if(!move_uploaded_file($f['tmp_name'],$target))out(['error'=>'Файлът не може да бъде записан.'],500);$rel=substr($target,strlen(__DIR__)+1);$now=date(DATE_ATOM);if($old){$oldp=__DIR__.'/'.$old['stored_path'];if($oldp!==$target&&is_file($oldp))@unlink($oldp);$s=db()->prepare('UPDATE offers SET original_name=?,stored_path=?,client=?,offer_date=?,updated_at=? WHERE id=?');$s->execute([basename($f['name']),$rel,$client,$date,$now,$id]);}else{$s=db()->prepare('INSERT INTO offers(offer_no,original_name,stored_path,client,offer_date,author,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$no,basename($f['name']),$rel,$client,$date,$_SESSION['user'],$now,$now]);}out(['ok'=>true,'offer_no'=>$no]);}
if($a==='download'){auth();$s=db()->prepare('SELECT * FROM offers WHERE id=?');$s->execute([(int)($_GET['id']??0)]);$o=$s->fetch(PDO::FETCH_ASSOC);if(!$o)out(['error'=>'Файлът не е намерен.'],404);$p=__DIR__.'/'.$o['stored_path'];if(!is_file($p))out(['error'=>'Файлът липсва.'],404);header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Length: '.filesize($p));header("Content-Disposition: attachment; filename*=UTF-8''".rawurlencode($o['original_name']));readfile($p);exit;}
if($a==='delete'&&$_SERVER['REQUEST_METHOD']==='POST'){auth();check();$i=json_decode(file_get_contents('php://input'),true)?:[];$s=db()->prepare('SELECT stored_path FROM offers WHERE id=?');$s->execute([(int)($i['id']??0)]);$p=$s->fetchColumn();if(!$p)out(['error'=>'Офертата не е намерена.'],404);@unlink(__DIR__.'/'.$p);$s=db()->prepare('DELETE FROM offers WHERE id=?');$s->execute([(int)$i['id']]);out(['ok'=>true]);}
}catch(Throwable $e){error_log($e->__toString());out(['error'=>'Вътрешна сървърна грешка. Проверете PHP error log.'],500);}
header('Content-Type: text/html; charset=utf-8');?>
<!doctype html><html lang="bg"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href="<?=htmlspecialchars(APP_BASE)?>/"><title>BP Строй Оферти</title><link rel="stylesheet" href="assets/style.css?v=2"></head><body>
<div id="fatal" class="fatal hidden"></div><section id="login" class="center hidden"><form id="loginForm" class="card auth"><div class="logo">▦</div><h1>BP Строй Оферти</h1><p>Управление на строително-ремонтни оферти</p><label>Потребителско име<input name="username" value="admin" required></label><label>Парола<input name="password" type="password" value="admin123" required></label><div id="loginError" class="error"></div><button>Вход</button><small>Тестов вход: admin / admin123</small></form></section>
<div id="app" class="hidden"><header><a href="<?=APP_BASE?>/" class="brand"><b>▦</b><span>BP Строй<small>Оферти</small></span></a><div><span id="who"></span><button id="manageUsers" class="ghost hidden">Потребители</button><button id="logout" class="ghost">Изход</button></div></header><main><div class="title"><div><h1>Excel оферти</h1><p>Съхранение, преглед и редакция</p></div><button id="new">+ Нова оферта</button></div><div class="stats"><article><b id="nFiles">0</b>Файла</article><article><b id="nClients">0</b>Клиента</article><article><b id="nAuthors">0</b>Автори</article></div><div class="card filters"><input id="q" placeholder="Търсене"><select id="client"><option value="">Всички клиенти</option></select><select id="author"><option value="">Всички автори</option></select><input id="from" type="date"><input id="to" type="date"><button id="clear" class="secondary">Изчисти</button></div><div class="card table"><table><thead><tr><th>Файл</th><th>Клиент</th><th>Дата</th><th>Автор</th><th></th></tr></thead><tbody id="rows"></tbody></table><p id="empty" class="empty hidden">Няма намерени оферти.</p></div></main></div>
<div id="modal" class="modal hidden"><div class="dialog"><div class="dialogHead"><div><small id="mode">Нова оферта</small><h2 id="caption">Excel редактор</h2></div><button id="close" class="ghost">✕</button></div><div class="dialogBody"><div class="meta"><label>Клиент<input id="mClient"></label><label>Дата<input id="mDate" type="date"></label><label>Име на файл<input id="mName"></label></div><div class="toolbar"><input id="upload" type="file" accept=".xlsx"><button id="add" class="secondary">+ Ред</button><button id="save">Запази Excel</button></div><div id="tabs" class="tabs"></div><div class="grid"><table><thead id="head"></thead><tbody id="body"></tbody></table></div><p class="note">Редакторът визуализира първите 300 реда. Формулите в качени файлове се запазват, но редактирана клетка се записва като стойност.</p></div></div></div>

<div id="usersModal" class="modal hidden"><div class="dialog usersDialog"><div class="dialogHead"><div><small>АДМИНИСТРАЦИЯ</small><h2>Управление на потребители</h2></div><button id="closeUsers" class="ghost">✕</button></div><div class="dialogBody"><form id="userCreate" class="userCreate"><label>Потребителско име<input name="username" minlength="3" maxlength="50" required></label><label>Начална парола<input name="password" type="password" minlength="8" required></label><label>Роля<select name="role"><option value="user">Потребител</option><option value="admin">Администратор</option></select></label><button>Създай потребител</button></form><div id="userError" class="error"></div><div class="userTable"><table><thead><tr><th>Потребител</th><th>Роля</th><th>Създаден</th><th></th></tr></thead><tbody id="userRows"></tbody></table></div><p class="note">Администраторът не може да изтрие активния си профил или последния администратор.</p></div></div></div>
<script>window.APP_BASE=<?=json_encode(APP_BASE)?>;</script><script src="assets/app.js?v=2"></script></body></html>
